### PR TITLE
feat: nodex project browser interface

### PR DESCRIPTION
**Pull request by yurireeis**
how to test:

just checkout to this branch and run:

`node build.js`

a new (ignored) folder will appear with the following structure:

```
index.html
app.js
styles.css
```

what's new:

- created a build.js script to generate a final html with each module examples and topics nested in an accordion structure
- less than 10ms to run and being available into an ignored build folder
- no angular/react/vue/jekill or any external libraries/frameworks included, because seems to be a little over engineering for this project (just used built-in libraries)

### CODE REVIEW

**Comment by atapas** [comment]
@yurireeis Suggest the deployment plan.

**Comment by yurireeis** [comment]
@atapas hi. follows a netlify url to access a live documentation version:

https://63476d0fdfc5580008c5d2bc--grand-banoffee-4971e4.netlify.app/

I'll put the instructions to deploy on README.md

**Comment by atapas** [comment]
> https://63476d0fdfc5580008c5d2bc--grand-banoffee-4971e4.netlify.app/

That will be great, and it is a very cool addition!!! I shall merge it after that and deploy it on my OSS Netlify account.

After the merge, I would suggest a few enhancements. Excited to get it in

@yurireeis

**Comment by yurireeis** [comment]
@atapas you're welcome! let dive into these improvements

**Comment by atapas** [comment]
> @atapas you're welcome! let dive into these improvements

Could you please add the deployment steps in Readme? I can merge it then.

**Comment by yurireeis** [comment]
@atapas done

**Review by atapas — APPROVED** [review]

**Pull request merged**
